#ifndef GPIO_H
#define GPIO_H

#include "stm32f103.h"

typedef enum {
  GPIO_MODE_INPUT = 0,
  GPIO_MODE_OUTPUT_2MHZ = 2,
  GPIO_MODE_OUTPUT_10MHZ = 1,
  GPIO_MODE_OUTPUT_50MHZ = 3
} gpio_mode_t;

typedef enum {
  GPIO_CNF_OUTPUT_PUSH_PULL = 0,
  GPIO_CNF_OUTPUT_OPEN_DRAIN = 1,
  GPIO_CNF_OUTPUT_AF_PUSH_PULL = 2,
  GPIO_CNF_OUTPUT_AF_OPEN_DRAIN = 3,

  GPIO_CNF_INPUT_ANALOG = 0,
  GPIO_CNF_INPUT_FLOATING = 1,
  GPIO_CNF_INPUT_PULL = 2
} gpio_cnf_t;


#endif